### ISSUE TITLE
(features/breadcrumb) cделать блок Breadcrumb (путь пользователя)

### ISSUE THREAD

**Issue by puinka** [pomazkovanton/liza-alert#15]

**Comment by puinka** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/30889583/168859024-c919dcba-d0d1-4dfb-bff1-092eb79c1a18.png">

**Comment by pomazkovanton** [comment]
- [ ] Для блока используйте упорядоченный список <ol>
- [ ] Блок должен быть на всех страницах проекта
- [ ] Придумать стили для активного элемента (disable / _active)
