### ISSUE TITLE
(features/video) cделать блок video

### ISSUE THREAD

**Issue by puinka** [pomazkovanton/liza-alert#16]
Блок видео (или картинка) и контролы к нему.

**Comment by pomazkovanton** [comment]
- [ ] Нужно реализовать нативными элементами HTML элемент управления плеером (можно использовать <input type=“range”> и его кастомную стилизацию).
- [ ] Вместо чёрного фона можно поставить картинку, а внутри (снизу) блок управления, написанный на нативном HTML и CSS.

![изображение](https://user-images.githubusercontent.com/18042030/168932827-6570ea83-099b-41e2-84af-a70b6569f029.png)
