### ISSUE TITLE
(features/action-panel) cделать блок action-panel

### ISSUE THREAD

**Issue by puinka** [pomazkovanton/liza-alert#17]
- [x] button primary
- [x] button secondary
*Думаю, для кнопок с иконками не нужны будут модификаторы, раз мы будет спрайтом пользоваться (use)*

**Comment by pomazkovanton** [comment]
- [ ] Можно сделать список ссылок, как при навигации (ul > li > a). Если предположить, что в теории может появится еще какая-нибудь кнопка в будущем, а можно просто div. 

![изображение](https://user-images.githubusercontent.com/18042030/168933285-c20c0a00-7476-4189-ae63-41a9d94abd1d.png)

**Comment by pomazkovanton** [comment]
Еще сейчас подумал, что у нас такой блок встречается по всем страницам, именно что две карточки рядом. Может написать универсальный класс?

![изображение](https://user-images.githubusercontent.com/18042030/168936104-357b7c50-c115-49c2-9023-4cdc2182ed39.png)

**Comment by pomazkovanton** [comment]
Блокирующая задача #18

**Comment by puinka** [comment]
Да, думаю это должен быть универсальный блок, почти pagination (но можно и так назвать)
