### ISSUE TITLE
(style/button) cделать стили для блока button

### ISSUE THREAD

**Issue by puinka** [pomazkovanton/liza-alert#18]
- [x] Primary
- [x] Secondary

**Плюс для каждой** 
- [ ] Focus
- [x] Hover
- [x] Active
- [x] Disabled

**Comment by pomazkovanton** [comment]
- [ ] Нужно предусмотреть универсальные стили, чтобы этот класс можно было повесить как на ссылку, так и на button. (Потому что сейчас это ссылку, но когда будет JS, они станут по семантике кнопками)

![изображение](https://user-images.githubusercontent.com/18042030/168933025-6a5dbdc0-8e16-4cdb-addd-e5931fd1b52b.png)
