### ISSUE TITLE
(style/card-container) cделать стили для блока card-container

### ISSUE THREAD

**Issue by puinka** [pomazkovanton/liza-alert#19]
На всех страницах используется белая карточка с тенью, меняется только контент. Предлагаю эту карточку (можно вместе с заголовком) вынести в отдельный блок. 
<img width="529" alt="image" src="https://user-images.githubusercontent.com/30889583/168861819-68f93c0e-9723-49d4-83f8-b1e92806dd9a.png">

Можно этот контейнер переиспользовать и для бокового меню тоже.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/30889583/168861897-85904987-ba76-4348-aec2-16db0a4d7c83.png">

**Comment by pomazkovanton** [comment]
Идея мне нравится! Я только за ) Единственное есть предложение насчет этого блока. может сделать его более универсальным? Например есть еще карточки, где есть еще и ссылка. Предлагаю сделать такую структуру card > (header_card > (title + link) / body_card > основной контент карточки )

Тогда нужно будет написать универсальные стили, чтобы когда ссылки в карточки нет, верстка не разваливалась.

![изображение](https://user-images.githubusercontent.com/18042030/168933970-f243f750-eb2b-49ba-b475-f440a87612ac.png)
