### ISSUE TITLE
(fix/video) сделать чтобы блок video растягивался вместе с родителем

### ISSUE THREAD

**Issue by pomazkovanton** [pomazkovanton/liza-alert#52]
![изображение](https://user-images.githubusercontent.com/18042030/169638266-16872644-3c05-4744-bf32-24c935cd131d.png)

**Comment by pomazkovanton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(fix/video) сделать чтобы блок video растягивался вместе с родителем #52](https://trello.com/c/kvWdHnd5/30-fix-video-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B1%D0%BB%D0%BE%D0%BA-video-%D1%80%D0%B0%D1%81%D1%82%D1%8F%D0%B3%D0%B8%D0%B2%D0%B0%D0%BB%D1%81%D1%8F-%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B5-%D1%81-%D1%80%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%D0%BC-52)

**Comment by puinka** [comment]
Тут на странице не было сетки. Сейчас я ее добавила и все работает. 
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/30889583/169640836-4d74db43-0e41-4681-9e61-2644f6fcf09b.png">
@pomazkovanton

**Comment by pomazkovanton** [comment]
Ага, сейчас увидел, но там все равсно какой-то зазор, либо картинка, либо блок видео)
![изображение](https://user-images.githubusercontent.com/18042030/169640947-458dbe9f-5a77-42bb-afea-afde4d08704f.png)

**Comment by pomazkovanton** [comment]
@puinka Да и видео не сжимается, если блок уменшать
![изображение](https://user-images.githubusercontent.com/18042030/169640973-4c5cfbaf-0cc4-459b-b047-3c9126df552d.png)

**Comment by puinka** [comment]
Залила исправление прямо в develop.

**Comment by puinka** [comment]
Здесь уже все исправлено, на сколько мне браузер показывает @pomazkovanton
