### ISSUE TITLE
(style/title) cделать стили для блока title

### ISSUE THREAD

**Issue by pomazkovanton** [pomazkovanton/liza-alert#7]
Нужно учесть следующие моменты и создать под них модификаторы:
- [ ] Два размера шрифта (48px и 24px)  title_size_s / title_size_l
- [ ] Три цвета (чёрный, красный и зеленый) title_type_success / title_type_error

HTML пока писать не нужно, только стили по БЭМ.

![image](https://user-images.githubusercontent.com/18042030/168799654-7481d726-e5c7-42ca-a0db-e04654ccb052.png)

**Comment by pomazkovanton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(features/title) Сделать стили для блока title #7](https://trello.com/c/gEr1klLJ/6-features-title-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D0%B8%D0%BB%D0%B8-%D0%B4%D0%BB%D1%8F-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0-title-7)

**Comment by pomazkovanton** [comment]
Дополнение!!

Думаю это тоже по семантики сделать заголовками. То есть нужно добавить еще один модификатор для размера текста 18px.

Что думаете?

![изображение](https://user-images.githubusercontent.com/18042030/168938628-eb1405c8-172b-45ec-ab98-4cb7f43d72f7.png)

**Comment by puinka** [comment]
Да, "учебная платформа" И так далее - это тоже заголовки
