### ISSUE TITLE
(style/css-checkboxes) cделать кастомные чекбоксы

### ISSUE THREAD

**Issue by puinka** [pomazkovanton/liza-alert#9]

**Comment by pomazkovanton** [comment]
- [ ] Label нужно будет связать с input
- [ ] Клик должен происходить не только по самому чекбоксу, но и лейблу

[Отличная видео инструкция](https://www.youtube.com/watch?v=E6kLaaQFctU&t=1404s)

![изображение](https://user-images.githubusercontent.com/18042030/168936200-da68764a-2005-4394-97b5-587c6e7db2c4.png)
